/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./public/**/*.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material You design tokens (resolved from CSS custom properties)
        'surface-bright': 'rgb(var(--surface-bright-rgb) / <alpha-value>)',
        'surface': 'rgb(var(--surface-rgb) / <alpha-value>)',
        'background': 'rgb(var(--background-rgb) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--surface-container-lowest-rgb) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--surface-container-low-rgb) / <alpha-value>)',
        'surface-container': 'rgb(var(--surface-container-rgb) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--surface-container-high-rgb) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--surface-container-highest-rgb) / <alpha-value>)',
        'surface-dim': 'rgb(var(--surface-dim-rgb) / <alpha-value>)',
        'surface-variant': 'rgb(var(--surface-variant-rgb) / <alpha-value>)',
        'surface-tint': 'rgb(var(--surface-tint-rgb) / <alpha-value>)',
        'primary': 'rgb(var(--primary-rgb) / <alpha-value>)',
        'primary-dim': 'rgb(var(--primary-dim-rgb) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--primary-fixed-rgb) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--primary-fixed-dim-rgb) / <alpha-value>)',
        'primary-container': 'rgb(var(--primary-container-rgb) / <alpha-value>)',
        'on-primary': 'rgb(var(--on-primary-rgb) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--on-primary-container-rgb) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--on-primary-fixed-rgb) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--on-primary-fixed-variant-rgb) / <alpha-value>)',
        'on-surface': 'rgb(var(--on-surface-rgb) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--on-surface-variant-rgb) / <alpha-value>)',
        'on-background': 'rgb(var(--on-background-rgb) / <alpha-value>)',
        'outline': 'rgb(var(--outline-rgb) / <alpha-value>)',
        'outline-variant': 'rgb(var(--outline-variant-rgb) / <alpha-value>)',
        'error': 'rgb(var(--error-rgb) / <alpha-value>)',
        'error-container': 'rgb(var(--error-container-rgb) / <alpha-value>)',
        'on-error': 'rgb(var(--on-error-rgb) / <alpha-value>)',
        'on-error-container': 'rgb(var(--on-error-container-rgb) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--inverse-surface-rgb) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--inverse-on-surface-rgb) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--inverse-primary-rgb) / <alpha-value>)',
        'secondary': 'rgb(var(--secondary-rgb) / <alpha-value>)',
        'secondary-container': 'rgb(var(--secondary-container-rgb) / <alpha-value>)',
        'on-secondary': 'rgb(var(--on-secondary-rgb) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--on-secondary-container-rgb) / <alpha-value>)',
        'tertiary': 'rgb(var(--tertiary-rgb) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--tertiary-container-rgb) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--on-tertiary-rgb) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--on-tertiary-container-rgb) / <alpha-value>)',
        'sage-peach': 'rgb(var(--sage-peach-rgb) / <alpha-value>)',
        'sage-peach-light': 'rgb(var(--sage-peach-light-rgb) / <alpha-value>)',
        // Hyperliquid page
        'hl-bg': '#090909',
        'hl-surface': '#111111',
        'hl-border': '#1e1e1e',
        'hl-green': '#68f5a5',
        // Polymarket page
        'pm-blue': '#0d2149',
        'pm-blue-light': '#1a3a6e',
        'pm-accent': '#325bff',
        'pm-accent-light': '#eef1ff',
      },
      fontFamily: {
        headline: ['Outfit'],
        body: ['Outfit'],
        label: ['Outfit'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
